# Generated by Django 3.2.9 on 2021-11-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер')),
                ('old_number', models.CharField(max_length=20, verbose_name='Старый номер')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('about', models.TextField(verbose_name='Описание')),
                ('etc', models.CharField(max_length=255, verbose_name='Заметка')),
                ('cab', models.CharField(max_length=50, verbose_name='Кабинет')),
                ('date', models.DateField(verbose_name='Дата принятия')),
                ('balanse', models.CharField(max_length=100, verbose_name='Баланс')),
                ('balanse_now', models.CharField(max_length=100, verbose_name='Остаточная')),
            ],
        ),
    ]
